### ISSUE TITLE
Auto-claim rewards

### ISSUE THREAD

**Issue by clubpetey** [FTBTeam/FTB-Quests#127]
When building a command reward, it would be great to have a flag that indicated this reward should be hidden.  

Hidden command rewards would run automatically when the quest was completed, they would not need to be "clicked" to be received.

Along with this, a setting to create a custom toast would be great.  I know you could use the command to say something to the team/player in chat, but the toast would be a nicer UI experience.

**Comment by iComputerfreak** [comment]
I'm playing FTB Sky Odyssey right now and have the problem that we need to claim a repeatable quest about 300 times now to complete the pack. So an auto claim feature would also be nice for the money rewards.

Maybe you could add an option on the reward side to set like a check box "auto claim" and the player who checked the box would get the money (which could be hard, if the player is offline).

Another option would be to make the repeatable quests stackable, so that you can begin to submit the next 50,000 Buckets without having to claim the reward first (and then be able to claim like 100,000 $ at once).
This way one could submit the quests over night automatically.
