### ISSUE TITLE
Remote/offsite quest storage/updates

### ISSUE THREAD

**Issue by kreezxil** [FTBTeam/FTB-Quests#147]
Like your ftb guides, it would be awesome to have data for quests stored offsite or remotely. This advantageous for quick pack updates for quests when it is just quests, or making sure the quests are synchronized across servers of the same pack.

The possibilities would be endless.

Default option should be not remote ofcourse.

**Comment by LatvianModder** [comment]
That's actually how it was supposed to work at first. We had plans for event-based quests, like halloween or april fools but that idea was scrapped back then because we didn't have the right server setup for that.  The idea was that server owners could even download their own DLC quest trees and users could upload their own on our site or curseforge. Now that I have split the quest file however, I will revisit the idea.
