### ISSUE TITLE
JEI Integration

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Quests#18]
- ~~R and U can be pressed on items in quests GUI~~
- R on item shows if it can be get from quest rewards
- U on item shows it's use in quest tasks
- ~~R on loot crate shows from which mobs they are dropped with chances~~
- ~~U on loot crate shows all possible drops with chances (if not hidden)~~
- Show all loot crates properly in JEI

**Comment by CrankySupertoon01** [comment]
oooh

**Comment by generrosity** [comment]
Yup just watched a video where two tubers were looking for what was a quest item

**Comment by DearDeathDay** [comment]
For further integration could it be made so that from the quest page one can click something or some such to auto-fill in the search request in JEI. For example, if the quest was to craft a chest shift+clicking or something on the icon would show the JEI recipe for the item. I feel like this would be a cool implementation to improve quality of life slightly.

**Comment by LatvianModder** [comment]
Updated description of issue
