### ISSUE TITLE
Optimalization problem and suggestions

### ISSUE THREAD

**Issue by vkub4plv** [FTBTeam/FTB-Quests#255]
I'm writing this post because my last one was closed, despite not mentioning even half of things in it, so. I'm saying about this post: #245. So good, that these things, that you wrote about are implemented, but what about rest of them?:
Option to copy quests / trees / move quests between trees / copy quests from one tree to another
Set dependencies to multiple quests (from the one in tree and from the one available from the edition mode) / move multiple quests at once
And what about problem, that I mentioned?

**Comment by Clem-Fern** [comment]
About your problem of lagging, some people report it too ( #237 & #226 )
Now, we have to wait for a fix

**Comment by LatvianModder** [comment]
That's because each suggestion/bug should be its own issue so I can oversee them more easily. 
https://github.com/FTBTeam/FTB-Quests/issues/275

You can move multiple quests at once, Ctrl+click to select them, then press Ctrl+Arrow to move the block. Its in [wiki](https://minecraft.curseforge.com/projects/ftb-quests/pages/about)
