### ISSUE TITLE
Quests reset after server restart for all player

### ISSUE THREAD

**Issue by DreiPixel** [FTBTeam/FTB-Quests#368]
im running a server with the pack Antimatter Chemistry and after several server restarts (every day) the latest restart reset all quests (except 1 sidequsts chapter).
this is actually the second time this happened for no reason. no crashes or anything.

using Ftbquest 1.8.0.237 and FTBlib 5.4.4.5

**Comment by Gibblesss** [comment]
I have this same issue with the modpack: M.C. Eternal, after 4 hour scheduled restarts, the questing mod resets all progress... its very random, it will sit for weeks or it will reset after the next restart.

**Comment by VallenFrostweaver** [comment]
Can confirm the same thing for MC.Eternal

**Comment by disduke** [comment]
yeah the same thing happened to me on mc.eternal

**Comment by disduke** [comment]
a similar thing happened to me on a single player world when the world started the backup my quest was reset

**Comment by Kakorot100000** [comment]
I also had the same issue on MC Eternal Server with the latest update, keep having to restore world from a backup every time it happens.

**Comment by mpavkovic** [comment]
Same, MC Eternal modpack, my game crashed in singleplayer and when I entered the world again all quests were reset.

How can I restore questbook from backups without rolling back world?

**Comment by Saphrym** [comment]
Can also confirm for FTB Interactions.

**Comment by MaxNeedsSnacks** [comment]
This issue is weird because neither me nor Lat have been able to reproduce it reliably, but either way it hopefully shouldn't exist anymore in newer FTB Quests releases (for versions 1.16 and up, as 1.12 is unsupported)

As for this:

> How can I restore questbook from backups without rolling back world?
@mpavkovic For future reference, the backed up world folder should contain a subfolder "ftbquests" which contains all the quest data at the time, that way you won't have to restore the entire world to that point

**Comment by TheNimbleNinja** [comment]
im having my quests reset on my 1.16 modpack and become not completable and its bringing me down quite a bit
