### ISSUE TITLE
[1.12.2] game hangs and closes when i bring up the text editor

### ISSUE THREAD

**Issue by free-muffin** [FTBTeam/FTB-Quests#573]
opened the text editor to write a description for a quest, popped up with a blank window and the game closed after about 5 seconds. no crashlog, nothing in my latest.log, the only feedback i got was an exit code 0 on the launcher.

started happening after a java update, currently running 1.8.0_291-b10

**Comment by MaxNeedsSnacks** [comment]
1.12 is unsupported, unfortunately, since so much has changed since then that we can't easily "switch" between the codebases.
Maybe as an additional question, are you trying to use the physical (unfinished) Editor GUI or the ingame editor, because I haven't had any issues with the latter on either 1.12 or 1.16
